name: NaLaPIP
channels:
  - defaults
dependencies:
  - black
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - openai
  - pandas
  - pip
  - python=3.9
  - scipy
  - seaborn
  - tqdm
  - pip:
      - blinker==1.7.0
      - flask==3.0.0
      - flask-cors==4.0.0
      - itsdangerous==2.1.2
      - werkzeug==3.0.1
prefix: /data/julius_heitkoetter/miniconda3/envs/physlang
